#!/usr/bin/env node
// Vortex local-oracle daemon: runs the watchlist tracker, writes a "what's new" digest, surfaces it.
// Pure-fetch (search + RSS) — no browser launch. Run on a schedule via cron or a launchd/systemd service.
//
// Delivery (2026-07-23): every run with new items is pushed to Steve via ntfy AND appended to the
// Obsidian KB (so brain search indexes it and Claude sessions start briefed). The digest file at
// $VORTEX_TRACKER_DIR/latest-digest.md stays the machine-readable source the session hook reads.
import { AgentBrowser, track } from './packages/core/dist/index.js';
import { readFile, writeFile, appendFile, mkdir, access } from 'node:fs/promises';

const DIR = process.env.VORTEX_TRACKER_DIR || `${process.env.HOME}/.vortex-tracker`;
const DIGEST = `${DIR}/latest-digest.md`;
const LOG = `${DIR}/digest-log.jsonl`;
const KB_INTEL_DIR = `${process.env.HOME}/Avant-Futures-KB/Intel/Vortex-Tracker`;

function fmt(d) {
  const lines = [`# Vortex Tracker — new developments`, `_ran ${d.ranAt} · ${d.entities} entities · ${d.newMentions} new_`, ''];
  for (const [entity, v] of Object.entries(d.byEntity)) {
    if (!v.new.length) continue;
    lines.push(`## ${entity}  (${v.new.length} new / ${v.totalKnown} tracked)`);
    for (const m of v.new.slice(0, 8)) lines.push(`- ${m.title}${m.date ? ` _(${m.date.slice(0, 16)})_` : ''}\n  ${m.url}`);
    lines.push('');
  }
  if (d.newMentions === 0) lines.push('_nothing new since last run._');
  return lines.join('\n');
}

// NTFY_URL from env, falling back to ~/.avanti-brain.env (last assignment wins, same as shell sourcing).
async function ntfyUrl() {
  if (process.env.NTFY_URL) return process.env.NTFY_URL;
  try {
    const env = await readFile(`${process.env.HOME}/.avanti-brain.env`, 'utf8');
    const m = [...env.matchAll(/^(?:export\s+)?NTFY_URL=(\S+)/gm)];
    return m.length ? m[m.length - 1][1] : null;
  } catch { return null; }
}

async function pushNtfy(digest) {
  const url = await ntfyUrl();
  if (!url) return 'ntfy: no NTFY_URL';
  const lines = Object.entries(digest.byEntity)
    .filter(([, v]) => v.new.length)
    .map(([e, v]) => `${e} (${v.new.length}): ${v.new[0].title}`)
    .slice(0, 10);
  try {
    const res = await fetch(url, {
      method: 'POST',
      // HTTP header values are Latin-1 only — keep the title ASCII (em-dash breaks fetch).
      headers: { Title: `Vortex Tracker - ${digest.newMentions} new`, Tags: 'telescope' },
      body: lines.join('\n'),
    });
    return `ntfy: ${res.status}`;
  } catch (e) { return `ntfy: FAILED ${e?.message || e}`; }
}

// Append the run's digest to a per-day KB note. Skipped silently when the SSD/KB isn't mounted.
async function writeKb(digest, md) {
  try { await access(`${process.env.HOME}/Avant-Futures-KB`); } catch { return 'kb: not mounted'; }
  try {
    await mkdir(KB_INTEL_DIR, { recursive: true });
    const day = digest.ranAt.slice(0, 10);
    const path = `${KB_INTEL_DIR}/${day}.md`;
    let isNew = false;
    try { await access(path); } catch { isNew = true; }
    const header = isNew ? `# Vortex Tracker — ${day}\n\n> Auto-generated by tracker-daemon. Watchlist intel, junk-filtered. See [[Agent/MEMORY/project_vortex_tracker]].\n\n` : '\n---\n\n';
    await appendFile(path, header + md.split('\n').slice(2).join('\n') + '\n');
    return `kb: ${path}`;
  } catch (e) { return `kb: FAILED ${e?.message || e}`; }
}

const b = new AgentBrowser(); // track() is pure-fetch; never opened
try {
  const digest = await track(b, { perEntity: 6 });
  await mkdir(DIR, { recursive: true });
  await writeFile(DIGEST, fmt(digest));
  await appendFile(LOG, JSON.stringify({ ranAt: digest.ranAt, newMentions: digest.newMentions, byEntity: Object.fromEntries(Object.entries(digest.byEntity).map(([e, v]) => [e, v.new.length])) }) + '\n');

  let delivered = 'nothing new — no push';
  if (digest.newMentions > 0) {
    const results = await Promise.all([pushNtfy(digest), writeKb(digest, fmt(digest))]);
    delivered = results.join(' · ');
  }

  // Optional surfacing to Slack (set VORTEX_SLACK_WEBHOOK) — only when there's something new.
  if (digest.newMentions > 0 && process.env.VORTEX_SLACK_WEBHOOK) {
    const top = Object.entries(digest.byEntity).filter(([, v]) => v.new.length).map(([e, v]) => `*${e}* (${v.new.length}): ${v.new[0].title}`).join('\n');
    try { await fetch(process.env.VORTEX_SLACK_WEBHOOK, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: `🔭 Vortex tracker — ${digest.newMentions} new:\n${top}` }) }); } catch { /* */ }
  }
  console.error(`[vortex-tracker] ${digest.newMentions} new across ${digest.entities} entities → ${DIGEST} · ${delivered}`);
} catch (e) {
  console.error(`[vortex-tracker] FAILED: ${e?.message || e}`);
  process.exit(1);
}
process.exit(0);
