import { execSync } from 'child_process';
import { existsSync, readFileSync, unlinkSync, mkdtempSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import type { VortexPlugin, CrawlResult } from '@stevecortesp/vortex-core';

interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

interface TranscriptResult {
  language: string;
  segments: TranscriptSegment[];
  fullText: string;
  wordCount: number;
}

/**
 * YouTube transcript extractor plugin.
 * Uses yt-dlp to fetch video captions/subtitles.
 * Supports manual and auto-generated captions.
 *
 * Requires: yt-dlp installed (`pip install yt-dlp`)
 */
export function transcriptExtractor(options?: {
  language?: string;
  autoGenerated?: boolean;
  includeTimestamps?: boolean;
}): VortexPlugin {
  const lang = options?.language ?? 'en';
  const autoGen = options?.autoGenerated ?? true;
  const timestamps = options?.includeTimestamps ?? true;

  return {
    name: 'transcript-extractor',

    afterProcess(result: CrawlResult): CrawlResult {
      if (!isYouTubeVideoUrl(result.url)) return result;

      const videoId = extractVideoId(result.url);
      if (!videoId) return result;

      try {
        const transcript = fetchTranscript(videoId, lang, autoGen);
        if (!transcript) return result;

        // Build transcript markdown
        const transcriptMd = formatTranscript(transcript, timestamps);

        // Append transcript to existing markdown
        const markdown = result.markdown + '\n\n## Transcript\n\n' + transcriptMd;

        return {
          ...result,
          markdown,
          extracted: {
            ...result.extracted,
            transcript: {
              language: transcript.language,
              wordCount: transcript.wordCount,
              segments: transcript.segments,
              fullText: transcript.fullText,
            },
          },
        };
      } catch {
        // yt-dlp not installed or failed — return original result
        return result;
      }
    },
  };
}

function isYouTubeVideoUrl(url: string): boolean {
  try {
    const u = new URL(url);
    const isYT = u.hostname === 'www.youtube.com' || u.hostname === 'youtube.com'
      || u.hostname === 'm.youtube.com' || u.hostname === 'youtu.be';
    if (!isYT) return false;
    // Must be a video page
    return u.pathname === '/watch' || u.hostname === 'youtu.be';
  } catch {
    return false;
  }
}

function extractVideoId(url: string): string {
  try {
    const u = new URL(url);
    if (u.hostname === 'youtu.be') return u.pathname.slice(1);
    return u.searchParams.get('v') || '';
  } catch {
    return '';
  }
}

function fetchTranscript(videoId: string, lang: string, autoGen: boolean): TranscriptResult | null {
  const tmpDir = mkdtempSync(join(tmpdir(), 'vortex-transcript-'));
  const outputPath = join(tmpDir, 'sub');

  try {
    // Build yt-dlp command
    const subFlag = autoGen ? '--write-auto-sub' : '--write-sub';
    const cmd = `python3 -m yt_dlp ${subFlag} --sub-lang ${lang} --skip-download --sub-format srv1 -o "${outputPath}" "https://www.youtube.com/watch?v=${videoId}" 2>/dev/null`;

    execSync(cmd, { timeout: 30_000, stdio: 'pipe' });

    // Find the subtitle file
    const subFile = `${outputPath}.${lang}.srv1`;
    if (!existsSync(subFile)) return null;

    const xml = readFileSync(subFile, 'utf-8');
    unlinkSync(subFile);

    // Parse XML
    const segments: TranscriptSegment[] = [];
    const regex = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
    let m;
    while ((m = regex.exec(xml)) !== null) {
      const text = m[3]
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&#39;/g, "'")
        .replace(/&quot;/g, '"')
        .replace(/<[^>]+>/g, '')
        .trim();

      if (text) {
        segments.push({
          start: parseFloat(m[1]),
          duration: parseFloat(m[2]),
          text,
        });
      }
    }

    if (segments.length === 0) return null;

    const fullText = segments.map(s => s.text).join(' ');

    return {
      language: lang,
      segments,
      fullText,
      wordCount: fullText.split(/\s+/).length,
    };
  } catch {
    return null;
  } finally {
    // Cleanup temp dir
    try {
      const { rmdirSync } = require('fs');
      rmdirSync(tmpDir, { recursive: true });
    } catch {}
  }
}

function formatTranscript(transcript: TranscriptResult, includeTimestamps: boolean): string {
  if (!includeTimestamps) {
    return transcript.fullText;
  }

  return transcript.segments.map(seg => {
    const min = Math.floor(seg.start / 60);
    const sec = Math.floor(seg.start % 60);
    return `**[${min}:${sec.toString().padStart(2, '0')}]** ${seg.text}`;
  }).join('\n');
}
